services:
  - type: web
    name: microservice-content
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: FLASK_ENV
        value: production
